### ISSUE TITLE
Does radeon 7850 work well by your code?　

### ISSUE THREAD

**Issue by Yujif1Aero** [ProjectPhysX/FluidX3D#29] opened 2022-10-31 00:18 UTC
Hi,
Sory I have a question again.
I tyied to compute by msi radeon 7850 however I got some worning and an error.(I could biud your codes) I use windows10, Visual studio 2022, openCL1.2 from Intel® SDK For OpenCL™ Applications and intel CPUs.
Is msi radeon 7850 too old?
Best,

**Comment by Yujif1Aero** [comment] 2022-10-31 00:44
Sorry again, I found that I got an erorr at 166 line in the opencl.hpp. I run your code soonaly afetr I installed your codes.
How should I do?

**Comment by Yujif1Aero** [comment] 2022-11-03 13:01
Thank you for your replying. Ive got an error message that I put.
Ive tested your fantastic coeds on the newest Radeon drivers for my GPU (21.5.2)
Best,
![FluidX3D_ERORR](https://user-images.githubusercontent.com/116667889/199727327-16ba7dc6-83b0-44a1-abb8-d81b4e92ba3b.png)

**Comment by ProjectPhysX** [comment] 2022-11-03 14:26
Hi @Yujif1Aero, this is a duplicate of https://github.com/ProjectPhysX/FluidX3D/issues/4
I'm closing this duplicate issue here and let the other one open.
Some old AMD GPUs seem to have a bug in the driver. I will look into it.

**Closed by ProjectPhysX** 2022-11-03 14:26 UTC
